# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=0, null=True)),
                ('open', models.FloatField(default=0, null=True)),
                ('high', models.FloatField(default=0, null=True)),
                ('low', models.FloatField(default=0, null=True)),
                ('close', models.FloatField(default=0, null=True)),
                ('adjclose', models.FloatField(default=0, null=True)),
                ('volume', models.IntegerField(default=0, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Code')),
            ],
        ),
    ]
