# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
