# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco_ip', models.CharField(max_length=15)),
                ('sco_datetime', models.DateTimeField(auto_now_add=True)),
                ('sco_referer', models.URLField(blank=True, default='', null=True)),
                ('sco_current', models.URLField(blank=True, default='', null=True)),
                ('sco_agent', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('sco_method', models.CharField(blank=True, default='', max_length=6, null=True)),
            ],
        ),
    ]
